const appname ="Al-Abbas Seller App",
 login = "Login",
    welcome = "Hi, Welcome to",
    shopSettings = "Shop Setting",
    changeImage = "Change Image",
    messages = "Messages",
    editProfile = "Edit Profile",
    email = "Email",
    password = "Password",
    forgotPassword = "Forgot Password",
    anyProblem = "In case of any difficulty, contact administration",
    credit = "@Anagnos",
    popular = "Popular Products",
    emailHint ="eg. vendor@gmail.com",
    passwordHint ="* * * * * * ",
    orders = "Orders",
    products ="Products",
    settings = "Settings",
    unpaid = "Unpaid",
    rating = "Rating",
    totalSales = "Total Sales",
    featured  ="Featured",
    edit = "Edit",
    remove = "Remove",
    logout="Logout",
    save ="Save",
    name="User Name",
    loginTo = "Login to your Account",
    dashboard="Dashboard";


    //shop setting strings
    const nameHint = "eg. Vendor Name",
    shopDescHint = "Enter your shop Description",
    shopWebsiteHint = "eg. vendor.al-abbas.com",
    shopMobileHint = "eg. +917356495249",
    shopAdressHint = "eg. Near Darnia Hat",
    description = "Description",
    mobile ="Shop Mobile",
    website ="Shop Website",
    cinformPassword = "Confirm Password",
    shopname = "Shop Name",
    address = "Shop Address";

